Sistema_Start/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
  
urlpatterns = [  
    # normal
    path('admin/', admin.site.urls),
    path('', include('webpage.urls')),  
	path('accounts/', include('accounts.urls')),
    path('painel/', include('painel.urls')),
    path('recursoshumanos/', include('recursoshumanos.urls')),
    path('administrador/', include('administrador.urls')),
    path('usuarios/', include('usuarios.urls')), 

    path('cadastro/', include('cadastro.urls')), 
    path('paciente/', include('paciente.urls')), 
    path('relatorio/', include('relatorio.urls')), 
    path('servicos/', include('servicos.urls')),  


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import (
	UserLogin,
	UserCreate,
	UserChange,
	PasswordChange,
	PasswordReset,
	PasswordResetConfirm,
	PasswordResetComplete,
	UserDelete,
	UserListView
)

from django.contrib.auth.views import (
	PasswordResetDoneView,
)


urlpatterns = [
	path('login/', UserLogin.as_view(), name='login'),
	path('user-new/', UserCreate.as_view(), name='user-new'),
	path('usuarios/', UserListView.as_view(), name='users'),
	path('<int:pk>/update/', UserChange.as_view(), name='user-change'),
	path('password-change/', PasswordChange.as_view(), name='password-change'),
	path('password-reset/', PasswordReset.as_view(), name='password-reset'),
	path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name="password_reset_confirm"),
	path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
	path('<int:pk>/delete/', UserDelete.as_view(), name='user-delete'),
	path('', include('django.contrib.auth.urls')),
]

base/urls.py
from django.urls import path


urlpatterns = [

]

usuarios/urls.py
from django.urls import path
from usuarios.views import (IndexUsuariosView)


urlpatterns = [
	path('', IndexUsuariosView.as_view(), name='index-usuarios'), 
] 

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):

		if not email:
			raise ValueError('E-mail é obrigatório')

		email = self.normalize_email(email)
		user = self.model(email=email, username=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):

		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):

		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('is_staff', True)

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser need to be is_superuser=True')

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser need to be is_staff=True')

		return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):

	DEPARTMENT_CHOICES = (
		('ad', 'Administração'),
		('rh', 'Recursos Humanos'),
		('us', 'Usuario Padrão')
	)
 
	is_staff = models.BooleanField('Team member', default=True)
	is_active = models.BooleanField('active', default=False)
 
	email = models.EmailField('Email', unique=True) 
	department = models.CharField(
		'Departamento',
		max_length=2,
		choices=DEPARTMENT_CHOICES
	)
	

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['first_name', 'last_name', 'department', 'is_active']

	class Meta:
		verbose_name = 'Usuário'
		verbose_name_plural = 'Usuários'
		ordering = ['first_name']

	def __str__(self):
		return self.email

	objects = UserManager()

usuarios/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm 
from accounts.models import CustomUser

class CustomUserCreateForm(UserCreationForm): 

	class Meta():
		model = CustomUser
		fields = ('first_name', 'last_name', 'username', 'department')
		labels = {'username': 'Username/Email'}

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		user.email = self.cleaned_data["username"]

		if commit:
			user.save()

		return user
 
class CustomUserChangeForm(UserChangeForm):

	class Meta():
		model = CustomUser
		fields = ('first_name', 'last_name', 'username', 'department', 'is_active')
		labels = {'username': 'Usuário'}

	def save(self, commit=True):
		user = super().save(commit=False)
		user.email = self.cleaned_data["username"]

		if commit:
			user.save()

		return user

accounts/views.py
from django.db.models.base import Model
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from base.base_admin_permissions import BaseAdminUsersAd
from accounts.forms import CustomUserCreateForm, CustomUserChangeForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from accounts.models import CustomUser
from django.views.generic import ListView
from django.contrib.auth.views import (
	LoginView,
	PasswordChangeView,
	PasswordResetView,
	PasswordResetConfirmView,
	PasswordResetCompleteView,
	)


class UserLogin(SuccessMessageMixin, LoginView):
	template_name = 'accounts/login.html'
 
	def get(self, request, *args, **kwargs): 
		if self.request.user.is_authenticated:
			return redirect('index-administrador') 
		else:
			return self.render_to_response(self.get_context_data())

class UserCreate(SuccessMessageMixin, CreateView):
	model = CustomUser
	form_class = CustomUserCreateForm
	template_name = 'accounts/user-new.html'
	success_url = reverse_lazy('login')
	success_message = 'Bem Vindo(a)! Faça login para começar'


class UserChange(BaseAdminUsersAd, UpdateView):
	model = CustomUser
	form_class = CustomUserChangeForm
	template_name = 'accounts/user-change.html'
	success_url = reverse_lazy('index')
	success_message = 'Sua mudança de perfil foi bem-sucedida' 

class UserDelete(BaseAdminUsersAd, DeleteView):
	model = CustomUser
	success_url = reverse_lazy('index')
	template_name = 'accounts/user-delete.html'

	def get_success_url(self): 
		messages.success(self.request, self.success_message) 
		return reverse('users')


class PasswordChange(SuccessMessageMixin, PasswordChangeView):
	template_name = 'accounts/password-change.html'
	success_url = reverse_lazy('index')
	success_message = 'Sua mudança de senha foi bem sucedida'


class PasswordReset(SuccessMessageMixin, PasswordResetView):
	template_name = 'accounts/password-reset.html'


class PasswordResetConfirm(SuccessMessageMixin, PasswordResetConfirmView):
	success_message = 'Sua senha foi redefinida corretamente. Faça login para começar'


class PasswordResetComplete(SuccessMessageMixin, PasswordResetCompleteView):
	template_name = 'accounts/password-reset-complete.html'
	success_message = 'Sua senha foi redefinida corretamente. Faça login para começar'

	def get(self, request, *args, **kwargs):

		return redirect('login')

class UserListView(BaseAdminUsersAd, ListView):
	model = CustomUser
	template_name = 'accounts/usuarios.html' 

usuarios/views.py
from django.views.generic.base import TemplateView  
from base.base_admin_permissions import BaseAdminUsersall

class IndexUsuariosView(BaseAdminUsersall, TemplateView):
	template_name = 'usuarios/index-usuarios.html'

accounts/templates/accounts/login.html
{% extends 'base/_base_index.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block body_title %}{% endblock %}
{% block body_content %}
 {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
        </div>
        {% endif %}
<div class="text-center h-100">
    <main class="form-signin h-100"> 
        <img class="img-fluid" src="{% static 'base/images/download.gif' %}" alt="logo" width="250" height="250">
        <h1 class="h3 mb-3 fw-normal">Entrar</h1>
        <form method="POST" autocomplete="off" id="form-login">
            {% csrf_token %}
            <div class="col">
                <div class="form-group mt-3">
                    <label for="username">Email</label>
                    <input type="email" id="username" name="username" class="form-control item"
                        value="{{ request.POST.username }}" required autofocus>
                </div>
                <div class="form-group mt-3">
                    <label for="password">Senha</label>
                    <input type="password" id="password" name="password" class="form-control item" required>
                </div>
                <div class="form-group mt-3">
                    <button class="btn button_min" type="submit">Conecte-se</button>
                    <a class="btn button_min" href="{% url 'password-reset' %}">Esqueceu a
                        senha?</a>
                </div>
                <div class="form-group mt-3">
                    <a class="link-secondary" href="{% url 'user-new' %}">Registrar-se</a>
                    <a class="link-secondary" role="button" href="{% url 'index' %}">cancelar</a>
                </div>
            </div>
        </form>
        <p class="mt-5 mb-3 text-muted">© XYZ 9999</p>
    </main>
</div>
{% endblock %}

accounts/templates/accounts/password-change.html
{% extends 'base/_base_index.html' %}
{% block title %}Alterar a senha{% endblock %}
{% block body_title %}Alterar a senha{% endblock %}
{% block body_content %}
<div class="text-center">
    <div class="form-signin">
        <form method="post" class="form" autocomplete="off">
            {% csrf_token %}
            <div class="form-group mt-3">
                <label for="old_password">Senha Antiga<span style="color: red;">*</span></label>
                <input type="password" class="form-control item" id="old_password" name="old_password" required
                    autofocus>
            </div>
            <div class="form-group mt-3">
                <label for="new_password1">Senha Nova<span style="color: red;">*</span></label>
                <input type="password" class="form-control item" id="new_password1" name="new_password1" required>
                <small id="password-help" class="form-text text-muted">
                    Sua senha não pode ser muito semelhante às suas outras informações pessoais,
                    deve conter pelo menos 8 caracteres, não pode ser uma senha comumente usada
                    e não pode ser totalmente numérica.
                </small>
            </div>
            <div class="form-group mt-3">
                <label for="new_password2">Nova confirmação de senha<span style="color: red;">*</span></label>
                <input type="password" class="form-control item" id="new_password2" name="new_password2" required>
            </div>
            <div class="form-group mt-3">
                <button type="submit" class="button_min"
                    name="btn_cadastro_canal">Alterar</button>
                <a class="button_min" role="button" href="{% url 'index' %}">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password-reset-complete.html
<a href="{% url 'login' %}">Conectar-se</a>

accounts/templates/accounts/password-reset.html
{% extends 'base/_base_index.html' %} 
{% block title %}Redefinir Senha{% endblock %} 
{% block body_content %}
<div class="text-center">
    <div class="form-signin">
         <h4 class=" mb-3 ">Redefinir Senha</h4>
        <form class="form" method="POST" action="{% url 'password-reset' %}" autocomplete="off">
            {% csrf_token %} 
            <div class="col">
                <div class="form-group mt-3">
                    <label for="email">Email</label><br>
                    <input type="email" id="email" name="email" class="form-control item" required autofocus>
                </div>  
                <div class="form-group  mt-3">
                    <button class="button_min" type="submit">Redefinir senha</button>
                    <a class="button_min" role="button" href="{% url 'index' %}">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user-card.html
{% if not user_list.is_superuser %}
<tbody>
    <tr>
        <th scope="row">{{ user_list.id }}</th>
        <th scope="row">{{ user_list.first_name }} {{ user_list.last_name }}</th>
        <th scope="row">{{ user_list.username }}</th>
        <th scope="row">{{ user_list.get_department_display }}</th>
        <th scope="row">
            <a class="button_min" href="{% url 'user-change' user_list.pk %}">Ver</a>
            <a class="button_min" href="{% url 'user-change' user_list.pk %}">Alterar</a>
            <a class="button_min" href="{% url 'user-delete' user_list.pk %}"><i class="fas fa-trash"></i></a>
        </th>
    </tr>
</tbody>
{% endif %}

accounts/templates/accounts/user-change.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Alterar Usuário{% endblock %}
{% block body_title %}Alterar Usuário{% endblock %}
{% block main_content %}
{% load widget_tweaks %}
<div class="text-center">
    <div class="form-signin"> 
        <h4 class="mb-3">Ver/Alterar Usuário</h4>
        <form method="post" class="form" autocomplete="off">
            {% csrf_token %}
            <div class="form-group mt-3">
                <label for="username">Email</label>
                {% render_field form.username class="form-control form-control" id="username" name="username" %}
            </div> 
            <div class="form-group mt-3">
                <label for="department">departamento</label>
                {% render_field form.department class="form-control form-control" id="department" name="department" %}  
            </div> 
            <div class="form-group mt-3">
                <label for="username">Nome</label>
                {% render_field form.first_name class="form-control form-control" id="first_name" name="first_name" %}      
            </div> 
            <div class="form-group mt-3">
                <label for="username">Sobrenome</label>
                {% render_field form.last_name class="form-control form-control" id="last_name" name="last_name" %} 
            </div> 
            <div class="form-group mt-3">
                <label for="username"><code>Usuário ís_active ?</code></label>
                {% render_field form.is_active class="form-check-input" id="is_active" name="is_active" %}    
            </div> 
            <div class="form-group mt-3">
                <button type="submit" class="button_min" name="btn_cadastro_canal">Alterar</button>
                <a class="btn button_min" role="button" href="{% url 'users' %}">Cancelar</a>
            </div> 
        </form> 
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user-delete.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Deletar Usuario{% endblock %}
{% block main_content %}
<div class="text-center">
    <div class="form-signin"> 
        <h2>{{ object.first_name }} {{ object.last_name }}</h2>
        <p>Tem a certeza que deseja apagar este usuário?<br>
            Todos os dados serão removidos. </p> 
        <form method="POST" class="form" name="form_canal">
            {% csrf_token %}
            <div class="form-group">
                <button type="submit" class="button_min" name="btn_cadastro_canal">Sim</button>
                <a class="btn button_min" role="button" href="{% url 'users'%}">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user-new.html
{% extends 'base/_base_index.html' %}
{% load static %}
{% block title %}Novo Usuário{% endblock %}
{% block body_content %}
<div class="text-center">
    <main class="form-signup">
        <img class="img-fluid" src="{% static 'base/images/download.gif' %}" alt="logo" width="250" height="250">
        <h1 class="h3 mb-3 fw-normal">Entrar</h1>
        <form method="post" class="form" action="{% url 'user-new' %}" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="username">Email<span style="color: red;">*</span></label>
                        <input type="email" class="form-control item" id="username" name="username" required autofocus>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="department">Departamento<span style="color: red;">*</span></label>
                        <select class="form-control item" id="department" name="department" required>
                            {% for dp in form.department %}
                            {{ dp }}
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="first_name">Nome<span style="color: red;">*</span></label>
                        <input type="text" class="form-control item" id="first_name" name="first_name" required>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="last_name">Sobrenome<span style="color: red;">*</span></label>
                        <input type="text" class="form-control item" id="last_name" name="last_name" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="password1">Senha<span style="color: red;">*</span></label>
                        <input type="password" class="form-control item" id="password1" name="password1" required>
                        <small id="password-help" class="form-text text-muted">
                            Sua senha deve conter pelo menos 8 caracteres.
                        </small>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group mt-3">
                        <label for="password2">Confirmação da Senha<span style="color: red;">*</span></label>
                        <input type="password" class="form-control item" id="password2" name="password2" required>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <button type="submit" class="button_min" name="btn_cadastro_canal">Salvar</button>
                <a class="btn button_min" role="button" href="{% url 'index' %}">Cancelar</a>
                <div id="msgSubmit" class="h3 text-center hidden"></div>
            </div>
            <div class="form-group py-3">
                <a class="link-secondary" href="{% url 'login' %}">Conectar-se</a>
            </div>
        </form>
        <p class="mt-5 mb-3 text-muted">© XYZ 9999</p>
    </main>
</div>
{% endblock %}

accounts/templates/accounts/usuarios.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Usuários{% endblock %}
{% block body_title %}Usuários do sistema{% endblock %}
{% block main_content %}
<div class="col-6">
    <a class="button_min" href="{% url 'user-new' %}">Cadastrar Usuários</a>
</div> 
<div class="table-responsive">
    <table class="text-center table table-bordered rounded mt-3 shadow-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome User</th>
                <th scope="col">Email</th>
                <th scope="col">Departamento</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        {% for user_list in object_list %}
        {% include 'accounts/user-card.html' %}
        {% endfor %}
    </table>
    {% endblock %}
</div>